version: 2.1
orbs:
    cypress: cypress-io/cypress@1.24.0
jobs:
    typecheck:
        docker:
            - image: circleci/node:13.14.0
        parallelism: 1
        working_directory: ~/repo
        steps:
            - checkout
            - run: yarn install
            - run: yarn typecheck
    build:
        docker:
            - image: circleci/node:13.14.0
        working_directory: ~/repo
        parallelism: 1
        steps:
            - checkout
            - run: yarn install
            - run: yarn build
    test:
        docker:
            - image: circleci/node:13.14.0
        working_directory: ~/repo
        parallelism: 1
        steps:
            - checkout
            - run: yarn install
            - run: yarn test
    lint:
        docker:
            - image: circleci/node:13.14.0
        working_directory: ~/repo
        parallelism: 1
        steps:
            - checkout
            - run: yarn install
            - run: yarn lint
workflows:
    create-react-app-typescript-todo-example-2020:
        jobs:
            - typecheck
            - build
            - test
            - lint
            - cypress/install:
                  yarn: true
            - cypress/run:
                  requires:
                      - cypress/install
                  yarn: true
                  executor: cypress/base-14
                  browser: chrome
                  record: false     # record results on Cypress Dashboard
                  parallel: true      # split all specs across machines
                  parallelism: 1      # use 4 CircleCI machines to finish quickly
                  group: 'all tests'  # name this group "all tests" on the dashboard
                  start: 'yarn start'  # start server before running tests